SOURCES ?= playerEntity.cpp IRLed.cpp SendIrMessageControl.cpp dataToIrByteControl.cpp keypadControl.cpp IrReceiver.cpp bitDetector.cpp
HEADERS ?= Keypad.hpp
SEARCH  ?= 
RELATIVE ?= ../..
include $(RELATIVE)/Makefile.due