SOURCES ?= keypadControl.cpp 
HEADERS ?= StructData.hpp InitGameControl.hpp dataToIrByteControl.hpp playerEntity.hpp Keypad.hpp IRLed.hpp SendIrMessageControl.hpp DisplayController.hpp
SEARCH  ?= 
RELATIVE ?= ../..
include $(RELATIVE)/Makefile.due